image: docker
stages:
   - build
build-stage :
 stage: build
 script:
 - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
 - docker build -t teamtrakss/consumer-portal-frontend .
 - docker push teamtrakss/consumer-portal-frontend
 tags:
 - immersive-cgi-w7-dotnet